# Generated by Django 4.2 on 2025-09-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_storage_quota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='storage_quota',
            field=models.BigIntegerField(default=5368709120),
        ),
    ]
